### ISSUE TITLE
Clicking 'Start Now' Fails to run Execution Policy

### ISSUE THREAD

**Issue by vailster** [haircut/better-jamf-policy-deferral#10]
**Describe the bug**
Choosing the 'Start Now' option results in an error message.

**Python 3**

_Note:_ Issues opened without specifying one of the following options will be ignored.

- [x] I am using the [macadmins Python](https://github.com/macadmins/python) distribution that I installed on the affected Mac.
- [ ] I am using a Python 3 runtime I installed myself, and I updated the script's shebang to point to the that `python3` binary.

**To Reproduce**
1. Run the 'Prompt' policy
2. Select Start Now, click ok
4. Get error baked into the script 'A problem occurred processing your request. Please contact your administrator for assistance'

**Expected behavior**
To run the 'Execution' policy

**Error output**
'A problem occurred processing your request. Please contact your administrator for assistance'

Just to add, if the execution policy is deferred, it runs fine at the specified deferred time.

**Comment by haircut** [comment]
👋 @vailster 

I believe I've corrected this issue in [32a1308](https://github.com/haircut/better-jamf-policy-deferral/commit/32a1308ad39e0fbeaa25a7ebaed1c7a726da5d45). I was not correctly handling the bytes string returned by jamfHelper after the transition to Python 3.

Would you please copy the latest version of the script from the repository, then try your workflow again? Please let me know the result.

**Comment by vailster** [comment]
Thanks @haircut - gave it a test this morning. Looks like the error is gone when running the execution policy immediately. But, it seems now that the execution policy doesn't actually start, either immediately or when deferred.

**Comment by vailster** [comment]
Ignore me, I removed and re-added the script to Jamf again and this time it worked 🎉 
Thanks for your help @haircut 🙌

**Comment by vailster** [comment]
All working 👍
