### ISSUE TITLE
Fails on cleanup step

### ISSUE THREAD

**Issue by patgmac** [haircut/better-jamf-policy-deferral#3]
First time trying BJPD. It mostly worked, installed the updates after a 30 min deferral as expected, but then error'ed out during the cleanup, which left the LD in tact which causes future policy prompts to fail. 

Anything standout with the following traceback?

`Script result: Traceback (most recent call last):
File "/Library/Application Support/JAMF/tmp/better-jamf-policy-deferral.py", line 29, in 
from AppKit import NSWorkspace
File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/AppKit/__init__.py", line 12, in 
from AppKit._inlines import _inline_list_
ImportError: dlopen(/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/AppKit/_inlines.so, 2): Symbol not found: __dyld_process_info_notify_main
Referenced from: /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
Expected in: /usr/lib/libSystem.B.dylib
in /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication`

**Comment by haircut** [comment]
Thanks for letting me know Patrick.

The error indicates a problem importing the `NSWorkspace` module from `AppKit`, which is required for the "blocking app" functionality. I'm not sure why this fails to load on your system, however.

- Is this happening on a single test machine or have you reproduced it on multiple Macs? If so, are those Macs similarly configured? Can you try the script on another Mac?
- Are you aware of any modifications to the system Python 2.7 installation?
- What version of macOS are you running?

Hopefully we can figure this out!

**Comment by patgmac** [comment]
I can reproduce on a VM with that same OS base (10.12.3 image), but it doesn't seem to be happening on any other OS, or even that same OS on a MBP. I'll have to chalk it up to an oddity. It was my first test, so I jumped the gun thinking I was doing something wrong, but subsequent tests seem to be working. 

Thanks for the reply.
