### ISSUE TITLE
Option for deferral limit

### ISSUE THREAD

**Issue by Soteyy** [haircut/better-jamf-policy-deferral#7]
Is it in any way possible to set dynamic deferral limits in the script, maybe at "GUI_DEFER_OPTIONS"?
At our company we'd like to enforce certain policies at the end of the month, the JSS built-in version gives you the option to set a date as the deferral limit in Policies -> User Interaction in JAMF.

**Comment by kylejericson** [comment]
Yes can we get this added.

**Comment by haircut** [comment]
@Soteyy Can you please clarify the request?

I _think_ I understand that you're asking that instead of providing options only for _n seconds from time of policy execution_ you're asking for the script to be able to instead provide a "do this at the end of the month" type option?

**Comment by Soteyy** [comment]
@haircut Yes, this is exactly what I mean!

**Comment by haircut** [comment]
I'm closing this issue since I don't have any intention to add new functionality to this tool.
