### ISSUE TITLE
Blocking Apps clarification

### ISSUE THREAD

**Issue by thunder-god-cid** [haircut/better-jamf-policy-deferral#8]
Hey there - looking at implementing this. What's the behavior when a blocking app is closed? I've found a good way to differentiate between "I have Zoom running" and "I'm actually in a zoom meeting", and I'd like to be able to use the Blocking App function to wait for someone to be out of a meeting.

**Comment by haircut** [comment]
I'm closing this issue since I don't have any intention to add new functionality to this tool.

**Comment by haircut** [comment]
I'm closing this issue since I don't have any intention to add new functionality to this tool.
